development:
  clients:
    default:
      uri: mongodb+srv://localhost:27017/tinycms_dev?retryWrites=true&w=majority
      options:
        server_selection_timeout: 5

test:
  clients:
    default:
      uri: mongodb+srv://localhost:27017/tinycms_test?retryWrites=true&w=majority
      options:
        server_selection_timeout: 5
        read:
          mode: :primary
        max_pool_size: 1
